security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/validateUser
server:
  port: 9090






spring:
 datasource:
  url: jdbc:mysql://localhost:3306/sample
  username: root
  password: 1234
 jpa: 
  hibernate.ddl-auto: update
  show-sql: true
 user.datasource.driver-class-name: com.mysql.jdbc.Driver
  
  